version: '2'
services:
  httpd:
    image: httpd
    volumes:
    - __httpd_conf__:/usr/local/apache2/conf
    - __httpd_static__:/usr/local/apache2/htdocs
    network_mode: "host"
    container_name:
      httpd

  web:
    image: registry.cn-hangzhou.aliyuncs.com/bismarckkk/management_web:1.0
    ports:
    - __web_port__:__web_port__
    volumes:
    - __config__:/code/config
    container_name:
      web

  wx:
    image: registry.cn-hangzhou.aliyuncs.com/bismarckkk/management_backend:1.0
    ports:
      - __wx_port__:__wx_port__
    volumes:
      - __config__:/code/config
    container_name:
      wx_backend

  webhook:
    image: registry.cn-hangzhou.aliyuncs.com/bismarckkk/webhook:1.0
    ports:
      - __webhook_port__:__webhook_port__
    volumes:
      - __config__:/code/config
    container_name:
      webhook